    - name: Update apt
      apt:
        upgrade: safe

    - name: Install ufw
      apt:
        name: ufw
        state: present
      
    - name: UFW settings outgoing
      ufw:
        default: allow
        direction: outgoing
    
    - name: UFW setting incoming
      ufw:
        default: deny
        direction: incoming

    - name: UFW rules ssh
      ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: UFW rules http
      ufw:
        rule: allow
        port: "80"
        proto: tcp 
    
    - name: UFW rules https
      ufw:
        rule: allow
        port: "443"
        proto: tcp
    
    - name: Allow k3s ports
      ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      loop:
        - { port: '6443', proto: 'tcp' }
        - { port: '10250', proto: 'tcp' }
        - { port: '8472', proto: 'udp' }
        - { port: '10248', proto: 'tcp' }
      when: >
        (inventory_hostname in groups['k3s_master'] and item.port == '6443') or
        (inventory_hostname in groups['k3s_worker'] and item.port in ['10250','8472','10248'])


    - name: UFW enabled
      ufw:
        state: enabled

    - name: Install base
      apt:
        name:
          - git
          - curl
          - unzip
          - htop
        state: present
