- name: Setting infrastructure
  hosts: vps
  become: true
  roles:
    - role: common

- name: k3s master
  hosts: k3s_master
  become: true
  roles:
    - role: k3s_master
  
- name: k3s workers
  hosts: k3s_worker
  become: true
  roles:
    - role: k3s_worker