name: CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Installing terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.6"

      - name: Get changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            terraform:
              - '**/*.tf'
            k8s:
              - 'k8s/*.yml'
      
      - name: Write service account key
        run: echo '${{ secrets.YC_SA_JSON_CREDENTIALS }}' > key.json
      
      - name: Write meta file
        run: echo '${{ secrets.TF_META }}' > meta.txt

      - name: Terraform init
        run: terraform init
      
      - name: Terraform plan
        id: plan
        run: |
          terraform plan \
          -no-color \
          -var="sa_key_file=key.json" \
          -var="cloud_id=${{ secrets.YC_CLOUD_ID }}" \
          -var="folder_id=${{ secrets.YC_FOLDER_ID }}" \
          -var="meta_file=meta.txt"
        continue-on-error: true
      
      
      - name: Comment PR
        if: github.event_name == "pull_request"
        uses: actions/github-script@v7
        with:
          script: |
            const output = `#### Terraform Plan
            \`\`\`
            ${{ steps.plan.outputs.stdout }}
            \`\`\`
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      
      
